### ISSUE TITLE
[enhancement] verification system 

### ISSUE THREAD

**Issue by yawn999** [suvanl/delet3#40]
user would have to verify before accessing channels. would be useful with if both anti-raid system and verification system would both be added,

**Comment by suvanl** [comment]
A verification system like that would be a great idea! Indeed it would be very useful if server mods/admins had both of these systems at their disposal. I'll start working on implementing both systems soon.

**Comment by yawn999** [comment]
actually, how would you be implementing the verification system? cause I kind of had the idea of like, a reaction to a message link, or a captcha.

**Comment by suvanl** [comment]
I was considering using [buttons](https://discordjs.guide/interactions/buttons.html#buttons) as they're now a thing in Discord.js v13. For example, a user uses a slash command (like `/verify`) and they are shown a message containing a button that they must click to verify themselves. This message would only be visible to the user who issues the command.

A captcha would be a great idea as it would be a more robust verification solution. However, I'm not entirely sure how this could be implemented as the Discord API doesn't support displaying captchas within the application. Perhaps the user is sent a link to a webpage containing a captcha, and once they've passed the captcha they'll receive a token which they must provide to the bot in order to pass verification?

**Comment by yawn999** [comment]
I love that idea! Were you thinking about adding a verification log? Just to see when a user verified and/or how fast they did it after they joined the server?

**Comment by suvanl** [comment]
Awesome!

Regarding logs, I was thinking of simply sending a "New User Verified" embed (containing info about the user, time, etc) to the mod log channel.

Although, now that you mention it, having a verification log where you can see all verification events in one place could be quite useful, so I think it might be a good idea to implement a setting where mods/admins can choose whether they want verification notifications to be sent to the regular mod log channel or to a separate verification log channel (or even both).

**Comment by suvanl** [comment]
Some of the more advanced features discussed here will be implemented in a future release. See the **Future** section in the description of #60.
